### ISSUE TITLE
Override New Actor Dialog

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#636]
### _Why:_ Is your feature request related to a problem?

As a GM (and maybe as a Player?), I want the default Create New Actor Dialog to be overridden to allow for some more specific choices:

- [ ] Choose a template from a list generated by rqid of template actors
- [ ] Name generator (re-usable UI component)
- [ ] Choose whether to start in Character Creation Mode

### _What:_ Describe the solution you'd like

Override the Create New Actor Dialog

### _Options:_ Describe alternatives you've considered

n/a

### Additional context

![image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/3959760/47434029-2269-4c21-8e39-b8466f2476be)

**Comment by Moonpile** [comment]
@wake42 Not sure if the checkboxes above warrant sub-issues.  Maybe only the name generator does?

**Comment by wake42** [comment]
I think that's up to how you want to organise it. Do sub issues if you want to / or not.

One thing to look out for is that currently there is only one actor type in the system, but when we add more (such as a party actor or similar) there is also a dropdown there in the same way as in the create item dialog. We should design so that still works.

**Comment by wake42** [comment]
Moving comments from a partly duplicate issue here:

Possibly pop up a dialog (or replace the standard dialog) when creating a new actor that lets you choose between a empty actor and a template actor containing hitlocations, runes & skills.
Possibly in _preCreate
Look at the L5R actor create dialog for inspiration.

Eventually the character creator could be a choice here, possibly replacing the template actor choice since that is part of the character creator.
